### ISSUE TITLE
How to move an atom to a certain vector direction

### ISSUE THREAD

**Issue by sumanchowdhury88** [AdityaRoy-1996/Phonopy_VESTA#2]
This program is running fine. But, I have a question, suppose I want to move a certain atom to a particular vector direction given by this code, what is the procedure for that?

**Comment by AdityaRoy-1996** [comment]
This code only visualises phonon eigenvectors. to create displacements, you can use the modulation tag in phonopy.

**Comment by AdityaRoy-1996** [comment]
Lets say you want to displace a particular atom by 2 angstrom, you have to find the unit vector along that direction, multiply it with your required magnitude and then subtract or add the resulting vector to the initial position of the atom. This will give you the new position of the displaced atom in that direction.

you can find the eigenvector directions from the vectors option in edit menu.

Refer to basic vector algebra of lines of any basic math book.

**Comment by AdityaRoy-1996** [comment]
> Lets say you want to displace a particular atom by 2 angstrom, you have to find the unit vector along that direction, multiply it with your required magnitude and then subtract or add the resulting vector to the initial position of the atom. This will give you the new position of the displaced atom in that direction.
> 
> you can find the eigenvector directions from the vectors option in edit menu.
> 
> Refer to basic vector algebra of lines of any basic math book.
