### ISSUE TITLE
how to get the structure file of the atomic position after moving according to the vector

### ISSUE THREAD

**Issue by KK33999** [AdityaRoy-1996/Phonopy_VESTA#3]
Dear Professors,
 I want to know how to get the structure file of the atomic position after moving according to the vector.

**Comment by AdityaRoy-1996** [comment]
> Dear Professors, I want to know how to get the structure file of the atomic position after moving according to the vector.

Please look into MODULATION tag in Phonopy

**Comment by KK33999** [comment]
Thank you very much !
