### ISSUE TITLE
Phonon mode plot for more than 8 atoms

### ISSUE THREAD

**Issue by surasree1812** [AdityaRoy-1996/Phonopy_VESTA#4]
Hi, could you just tell me one thing how can I change the number of vector in extract_vectors_phonopy.py file?

**Comment by AdityaRoy-1996** [comment]
> Hi, could you just tell me one thing how can I change the number of vector in extract_vectors_phonopy.py file?

I did not understand your question properly. I dont think you have to edit anything in this code except the vector scaling. Please share me your input files as in the example file showed and possibly reexplain your issue clearly.

**Comment by surasree1812** [comment]
Hi, I want to plot for 64 atom for silicon.
Here is the POSCAR,
!    ibrav = 0, nat = 64, ntyp = 1
CELL_PARAMETERS bohr
   20.6591056419132713    0.0000000000000000    0.0000000000000000
    0.0000000000000000   20.6591056419132713    0.0000000000000000
    0.0000000000000000    0.0000000000000000   20.6591056419132713
ATOMIC_SPECIES
 Si   28.08550   Si.pbe-n-kjpaw_psl.0.1.UPF
ATOMIC_POSITIONS crystal
 Si   0.4375000000000000  0.4375000000000000  0.4375000000000000
 Si   0.9375000000000000  0.4375000000000000  0.4375000000000000
 Si   0.4375000000000000  0.9375000000000000  0.4375000000000000
 Si   0.9375000000000000  0.9375000000000000  0.4375000000000000
 Si   0.4375000000000000  0.4375000000000000  0.9375000000000000
 Si   0.9375000000000000  0.4375000000000000  0.9375000000000000
 Si   0.4375000000000000  0.9375000000000000  0.9375000000000000
 Si   0.9375000000000000  0.9375000000000000  0.9375000000000000
 Si   0.4375000000000000  0.1875000000000000  0.1875000000000000
 Si   0.9375000000000000  0.1875000000000000  0.1875000000000000
 Si   0.4375000000000000  0.6875000000000000  0.1875000000000000
 Si   0.9375000000000000  0.6875000000000000  0.1875000000000000
 Si   0.4375000000000000  0.1875000000000000  0.6875000000000000
 Si   0.9375000000000000  0.1875000000000000  0.6875000000000000
 Si   0.4375000000000000  0.6875000000000000  0.6875000000000000
 Si   0.9375000000000000  0.6875000000000000  0.6875000000000000
 Si   0.1875000000000000  0.4375000000000000  0.1875000000000000
 Si   0.6875000000000000  0.4375000000000000  0.1875000000000000
 Si   0.1875000000000000  0.9375000000000000  0.1875000000000000
 Si   0.6875000000000000  0.9375000000000000  0.1875000000000000
 Si   0.1875000000000000  0.4375000000000000  0.6875000000000000
 Si   0.6875000000000000  0.4375000000000000  0.6875000000000000
 Si   0.1875000000000000  0.9375000000000000  0.6875000000000000
 Si   0.6875000000000000  0.9375000000000000  0.6875000000000000
 Si   0.1875000000000000  0.1875000000000000  0.4375000000000000
 Si   0.6875000000000000  0.1875000000000000  0.4375000000000000
 Si   0.1875000000000000  0.6875000000000000  0.4375000000000000
 Si   0.6875000000000000  0.6875000000000000  0.4375000000000000
 Si   0.1875000000000000  0.1875000000000000  0.9375000000000000
 Si   0.6875000000000000  0.1875000000000000  0.9375000000000000
 Si   0.1875000000000000  0.6875000000000000  0.9375000000000000
 Si   0.6875000000000000  0.6875000000000000  0.9375000000000000
 Si   0.0625000000000000  0.0625000000000000  0.0625000000000000
 Si   0.5625000000000000  0.0625000000000000  0.0625000000000000
 Si   0.0625000000000000  0.5625000000000000  0.0625000000000000
 Si   0.5625000000000000  0.5625000000000000  0.0625000000000000
 Si   0.0625000000000000  0.0625000000000000  0.5625000000000000
 Si   0.5625000000000000  0.0625000000000000  0.5625000000000000
 Si   0.0625000000000000  0.5625000000000000  0.5625000000000000
 Si   0.5625000000000000  0.5625000000000000  0.5625000000000000
 Si   0.0625000000000000  0.3125000000000000  0.3125000000000000
 Si   0.5625000000000000  0.3125000000000000  0.3125000000000000
 Si   0.0625000000000000  0.8125000000000000  0.3125000000000000
 Si   0.5625000000000000  0.8125000000000000  0.3125000000000000
 Si   0.0625000000000000  0.3125000000000000  0.8125000000000000
 Si   0.5625000000000000  0.3125000000000000  0.8125000000000000
 Si   0.0625000000000000  0.8125000000000000  0.8125000000000000
 Si   0.5625000000000000  0.8125000000000000  0.8125000000000000
 Si   0.3125000000000000  0.0625000000000000  0.3125000000000000
 Si   0.8125000000000000  0.0625000000000000  0.3125000000000000
 Si   0.3125000000000000  0.5625000000000000  0.3125000000000000
 Si   0.8125000000000000  0.5625000000000000  0.3125000000000000
 Si   0.3125000000000000  0.0625000000000000  0.8125000000000000
 Si   0.8125000000000000  0.0625000000000000  0.8125000000000000
 Si   0.3125000000000000  0.5625000000000000  0.8125000000000000
 Si   0.8125000000000000  0.5625000000000000  0.8125000000000000
 Si   0.3125000000000000  0.3125000000000000  0.0625000000000000
 Si   0.8125000000000000  0.3125000000000000  0.0625000000000000
 Si   0.3125000000000000  0.8125000000000000  0.0625000000000000
 Si   0.8125000000000000  0.8125000000000000  0.0625000000000000
 Si   0.3125000000000000  0.3125000000000000  0.5625000000000000
 Si   0.8125000000000000  0.3125000000000000  0.5625000000000000
 Si   0.3125000000000000  0.8125000000000000  0.5625000000000000
 Si   0.8125000000000000  0.8125000000000000  0.5625000000000000

How will I plot it?

**Comment by surasree1812** [comment]
Hi,
Here in the unit cell, 16 atoms are present, but only for 8, we can write the vector. How to solve it?
#########################
SITET
  1        Zn1  0.5000 255 255   0 143 143 129 204  0
  2        Zn2  0.5000 255 255   0 143 143 129 204  0
  3        Zn3  0.5000 255 255   0 143 143 129 204  0
  4        Zn4  0.5000 255 255   0 143 143 129 204  0
  5        Ge1  0.6000   0   0 255 126 110 166 204  0
  6        Ge2  0.6000   0   0 255 126 110 166 204  0
  7        Ge3  0.6000   0   0 255 126 110 166 204  0
  8        Ge4  0.6000   0   0 255 126 110 166 204  0
  9        Sb1  0.8000   0 128   0 215 131  79 204  0
 10        Sb2  0.8000   0 128   0 215 131  79 204  0
 11        Sb3  0.8000   0 128   0 215 131  79 204  0
 12        Sb4  0.8000   0 128   0 215 131  79 204  0
 13        Sb5  0.8000   0 128   0 215 131  79 204  0
 14        Sb6  0.8000   0 128   0 215 131  79 204  0
 15        Sb7  0.8000   0 128   0 215 131  79 204  0
 16        Sb8  0.8000   0 128   0 215 131  79 204  0
  0 0 0 0 0 0
VECTR
    1   0.62979   0.67206   0.00038
    1 0 0 0 0
  0 0 0 0 0
    2  -0.67126  -0.62160   0.00000
    2 0 0 0 0
  0 0 0 0 0
    3  -0.14775  -0.81688  -0.00007
    3 0 0 0 0
  0 0 0 0 0
    4   0.81839   0.13888  -0.00000
    4 0 0 0 0
  0 0 0 0 0
    5   0.00386  -1.04712   0.58768
    5 0 0 0 0
  0 0 0 0 0
    6   1.04427  -0.01665  -0.58818
    6 0 0 0 0
  0 0 0 0 0
    7   1.04429  -0.01664   0.58819
    7 0 0 0 0
  0 0 0 0 0
    8   0.00575  -1.04658  -0.58749
    8 0 0 0 0
  0 0 0 0 0
0 0 0 0 0


##########################

**Comment by AdityaRoy-1996** [comment]
> Hi, Here in the unit cell, 16 atoms are present, but only for 8, we can write the vector. How to solve it? ######################### SITET 1 Zn1 0.5000 255 255 0 143 143 129 204 0 2 Zn2 0.5000 255 255 0 143 143 129 204 0 3 Zn3 0.5000 255 255 0 143 143 129 204 0 4 Zn4 0.5000 255 255 0 143 143 129 204 0 5 Ge1 0.6000 0 0 255 126 110 166 204 0 6 Ge2 0.6000 0 0 255 126 110 166 204 0 7 Ge3 0.6000 0 0 255 126 110 166 204 0 8 Ge4 0.6000 0 0 255 126 110 166 204 0 9 Sb1 0.8000 0 128 0 215 131 79 204 0 10 Sb2 0.8000 0 128 0 215 131 79 204 0 11 Sb3 0.8000 0 128 0 215 131 79 204 0 12 Sb4 0.8000 0 128 0 215 131 79 204 0 13 Sb5 0.8000 0 128 0 215 131 79 204 0 14 Sb6 0.8000 0 128 0 215 131 79 204 0 15 Sb7 0.8000 0 128 0 215 131 79 204 0 16 Sb8 0.8000 0 128 0 215 131 79 204 0 0 0 0 0 0 0 VECTR 1 0.62979 0.67206 0.00038 1 0 0 0 0 0 0 0 0 0 2 -0.67126 -0.62160 0.00000 2 0 0 0 0 0 0 0 0 0 3 -0.14775 -0.81688 -0.00007 3 0 0 0 0 0 0 0 0 0 4 0.81839 0.13888 -0.00000 4 0 0 0 0 0 0 0 0 0 5 0.00386 -1.04712 0.58768 5 0 0 0 0 0 0 0 0 0 6 1.04427 -0.01665 -0.58818 6 0 0 0 0 0 0 0 0 0 7 1.04429 -0.01664 0.58819 7 0 0 0 0 0 0 0 0 0 8 0.00575 -1.04658 -0.58749 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0
> 
> ##########################


@surasree1812  This code needs bands.yaml file generated from the phonopy. You can see in the example file to run your system properly. The input file you provided is not complete in terms of QE pw.x file and also there is no bands.yaml file to extract the vectors from. You can send me your complete simulation files of QE or else try doing it yourself, it is not that difficult.
